# Generated by Django 4.0.3 on 2022-03-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='firstname',
            field=models.CharField(default='firstname', max_length=100, verbose_name='Firstname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='surname',
            field=models.CharField(default='lastname', max_length=200, verbose_name='Surname'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
